title: "Carla Peñafiel Messmer"
author: "Carla Peñafiel"
description: "University of Chile"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "/assets/me.jpg"} 
  - {file: "index.md", title: "Home"}
  - {file: "README.md", title: "About me"}
  - {file: "Academic_CV_Carla_P.pdf", title: "CV"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "carla.penafiel@ug.uchile.cl"}
  - {title: Github, icon: github, url: "https://github.com/carlapenafiel"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/carlapenafielm"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
